evm: Make initialiser payable to allow WH transceiver registration
wormhole-foundation/example-native-token-transfers pull request #335
Opened 2024-03-22 19:10 UTC by djb15

We don't query the wormhole message fee to save gas. The call will revert if the fee amount is not exact.

2024-03-25 14:11 UTC, johnsaigle approved these changes
I think this looks good but I don't think I have the complete context for understanding the change. I'll defer to other reviewers here if they raise issues

2024-03-28 18:55 UTC, mdulin2 approved these changes
You added it to all of the proper locations. So, I think it's solid and ready to go.

2024-04-03 18:24 UTC, johnsaigle requested changes
Looks like there's a conflict with main

2024-04-03 19:05 UTC, djb15 commented on evm/src/NttManager/NttManager.sol
> +        if (msg.value != 0) {
It just prevents the deployer from locking ETH on the manager since we don't need any ETH there, just for the transceiver initialisations

2024-04-03 19:26 UTC, johnsaigle approved these changes

2024-04-03 21:56 UTC, RahulMaganti47 commented on evm/src/interfaces/INttManager.sol
> +    error UnexpectedMsgValue();
can you include `msg.value` in the error?

2024-04-03 22:06 UTC, RahulMaganti47 approved these changes

2024-04-03 22:36 UTC, merged