evm: Make Wormhole chainId the canonical chainId
wormhole-foundation/example-native-token-transfers pull request #364
Opened 2024-03-27 21:17 UTC by djb15

This probably needs some more discussion since it does tie us to Wormhole supported chains. However it does reduce the risk of a misconfig where an admin specified chain id isn't the same as the wormhole chain id for that chain.

We would also need to update the deployment scripts to support this change

2024-03-28 13:03 UTC, johnsaigle requested changes
Needs some more updates to the test suite in order to pass CI.

Do we need the ABI label for this PR?

2024-03-28 18:30 UTC, mdulin2 commented
I agree, probably worth more discussion. 

From the Wormhole side, it makes sense to do this. I also have this check in my configuration checker script, for what's it's worth.

2024-03-29 17:53 UTC, RahulMaganti47 commented
> This probably needs some more discussion since it does tie us to Wormhole supported chains. However it does reduce the risk of a misconfig where an admin specified chain id isn't the same as the wormhole chain id for that chain.
> 
> We would also need to update the deployment scripts to support this change

imo not sure the wormhole chain id should be set as the default. this framework is meant to be more general anyway and integrators who choose to use the non-WH supported chains will have to configure it manually anyway. defaulting to it in the contracts makes this opinionated, which i don't think this is meant to be.

2024-04-02 20:42 UTC, djb15 commented
Closing this as the consensus is that we shouldn't force this coupling to Wormhole

2024-04-02 20:42 UTC, closed without merging