solana: Add Makefile targets to top-level dir
wormhole-foundation/example-native-token-transfers pull request #502
Opened 2024-08-21 19:40 UTC by nvsriram

This PR is based on #299.

* Makefile targets are renamed to sync with latest target names
* Lint command is updated to sync with latest [.github/workflows/solana.yml](https://github.com/wormhole-foundation/example-native-token-transfers/blob/main/.github/workflows/solana.yml) file command
* `all` Makefile target is removed to avoid confusion between EVM/Solana commands

2024-08-21 21:34 UTC, nonergodic requested changes
Generally speaking, this does not look like a particularly sensible Makefile to me. Nothing here depends on anything, it's really just a set of commands. There isn't even general targets to build/test/lint everything.

2024-08-21 21:34 UTC, nonergodic commented on Makefile
> +.PHONY: lint
```suggestion
.PHONY: lint-solana
```

2024-08-21 21:34 UTC, nonergodic commented on Makefile
>  test-push0:
```suggestion
.PHONY: test-push0
test-push0:
```

2024-08-27 14:46 UTC, nonergodic submitted a review, later dismissed
Eventually this should probably be split into 2 Makefiles - one for each subdir (evm, solana), but good enough for now.

2024-08-28 10:07 UTC, kcsongor commented
I want to echo @nonergodic's point here: I think we should be moving these targets into the subdirectory makefiles, instead of out of them. It looks like the makefile was moved to the top level in this PR https://github.com/wormhole-foundation/example-native-token-transfers/pull/147/files but I don't really see the reason why.

I think we should just move them back into the relevant subdirectories instead, and if someone wants to run these targets from the top-level, just do `make -C evm build` etc. It's a lot cleaner than ad-hoc namespacing the build targets.

2024-08-28 16:36 UTC, kcsongor commented on .github/workflows/evm.yml
> +          make -C evm push0-test
minor nit: it's possible to specify the working directory for all the commands here, like so:

https://github.com/wormholelabs-xyz/example-native-token-transfers/blob/8712337bb9ec20e6cf32ab70767789af1d0025f6/.github/workflows/solana.yml#L10-L12

2024-08-28 17:52 UTC, kcsongor approved these changes

2024-08-28 17:58 UTC, nonergodic approved these changes

2024-08-28 18:01 UTC, merged